"use client";
import { useState, useEffect, useCallback } from "react";
import { createClient } from "@supabase/supabase-js";
const sb=createClient("https://umwqxkggzrpwknptwwju.supabase.co","eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd3F4a2dnenJwd2tucHR3d2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUyNjgsImV4cCI6MjA4ODM1MTI2OH0.XL7OKT0C0OlX76_mQVcHXsAVXj8cq_mkLgSVJzyH0lc");
async function rpc<T>(fn:string,p:any={}):Promise<T>{const{data,error}=await sb.rpc(fn,p);if(error)throw error;return data as T;}
const SB="https://umwqxkggzrpwknptwwju.supabase.co",AK="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtd3F4a2dnenJwd2tucHR3d2p1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NzUyNjgsImV4cCI6MjA4ODM1MTI2OH0.XL7OKT0C0OlX76_mQVcHXsAVXj8cq_mkLgSVJzyH0lc";
async function call(u:string,b:any){try{await fetch(u,{method:"POST",headers:{"Content-Type":"application/json",Authorization:"Bearer "+AK},body:JSON.stringify(b)});}catch(_){}}
function fmt(d:string|null){return d?new Date(d).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";}
function ago(d:string|null){if(!d)return"";const m=Math.floor((Date.now()-new Date(d).getTime())/6e4);if(m<1)return"agora";if(m<60)return m+"min";const h=Math.floor(m/60);return h<24?h+"h":Math.floor(h/24)+"d";}
function md2h(t:string|null){if(!t)return"";return t.replace(/^### (.*$)/gm,'<h3 class="mh3">$1</h3>').replace(/^## (.*$)/gm,'<h2 class="mh2">$1</h2>').replace(/\*\*(.*?)\*\*/g,'<strong class="mb">$1</strong>').replace(/^- (.*$)/gm,'<div class="ml"><span class="md">\u2022</span><span>$1</span></div>').replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" class="ma">$1\u2197</a>').split("\n").map(l=>{const s=l.trim();return s?s.startsWith("<")?s:'<p class="mp">'+s+"</p>":'<br/>';}).join("");}
const V={g:"rgba(255,255,255,0.05)",t:"#eef2ff",s:"#c5cee0",m:"#7b89a8",l:"rgba(255,255,255,0.07)",a:"#7c9cff",a2:"#4ee3c1",r:"#ff6b6b",w:"#ffc86b",ok:"#6fe2a3",R:16};
const ST:Record<string,{bg:string;c:string;b:string}>={pending:{bg:"rgba(251,191,36,0.1)",c:"#fbbf24",b:"rgba(251,191,36,0.2)"},running:{bg:"rgba(59,130,246,0.1)",c:"#3b82f6",b:"rgba(59,130,246,0.2)"},completed:{bg:"rgba(34,197,94,0.1)",c:"#22c55e",b:"rgba(34,197,94,0.2)"},failed:{bg:"rgba(239,68,68,0.1)",c:"#ef4444",b:"rgba(239,68,68,0.2)"},passed:{bg:"rgba(34,197,94,0.1)",c:"#22c55e",b:"rgba(34,197,94,0.2)"},warning:{bg:"rgba(251,191,36,0.1)",c:"#fbbf24",b:"rgba(251,191,36,0.2)"},confirmed:{bg:"rgba(34,197,94,0.1)",c:"#22c55e",b:"rgba(34,197,94,0.2)"},ok:{bg:"rgba(34,197,94,0.1)",c:"#22c55e",b:"rgba(34,197,94,0.2)"},error:{bg:"rgba(239,68,68,0.1)",c:"#ef4444",b:"rgba(239,68,68,0.2)"}};
function B({s}:{s:string}){const c=ST[s]||ST.pending;return<span style={{display:"inline-block",padding:"2px 9px",borderRadius:20,fontSize:10,fontWeight:700,textTransform:"uppercase",letterSpacing:.6,background:c.bg,color:c.c,border:"1px solid "+c.b}}>{s}</span>;}
function Stat({label,value,icon,color}:{label:string;value:any;icon:string;color:string}){return<div style={{background:V.g,backdropFilter:"blur(12px)",border:"1px solid "+V.l,borderRadius:V.R,padding:"16px 18px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:-16,right:-16,width:60,height:60,borderRadius:"50%",background:color,filter:"blur(20px)",opacity:.5}}/><div style={{fontSize:18,opacity:.6,marginBottom:4}}>{icon}</div><div style={{fontSize:26,fontWeight:800,letterSpacing:-1.2,fontFamily:"'JetBrains Mono',monospace",color:V.t}}>{value}</div><div style={{fontSize:10,color:V.m,fontWeight:600,textTransform:"uppercase",letterSpacing:.8,marginTop:2}}>{label}</div></div>;}
function Card({children,style={}}:{children:any;style?:any}){return<div style={{background:V.g,backdropFilter:"blur(12px)",border:"1px solid "+V.l,borderRadius:V.R,padding:18,...style}}>{children}</div>;}
function Sec({title,icon,children,full=false}:{title:string;icon:string;children:any;full?:boolean}){return<div style={{background:"rgba(255,255,255,0.02)",border:"1px solid "+V.l,borderRadius:V.R,overflow:"hidden"}}><div style={{padding:"12px 18px",borderBottom:"1px solid "+V.l,display:"flex",alignItems:"center",gap:7}}><span style={{fontSize:15}}>{icon}</span><span style={{fontSize:12,fontWeight:700,color:"rgba(255,255,255,0.6)",textTransform:"uppercase",letterSpacing:.7}}>{title}</span></div><div style={{padding:"10px 14px",maxHeight:full?"none":320,overflowY:"auto"}}>{children}</div></div>;}

const TABS=[{id:"overview",l:"Overview",i:"\u26a1"},{id:"research",l:"Pesquisas",i:"\ud83d\udd0d"},{id:"evidence",l:"Evid\u00eancias",i:"\ud83e\uddea"},{id:"branches",l:"Ramos",i:"\ud83c\udf3f"},{id:"quality",l:"Quality",i:"\ud83d\udee1\ufe0f"},{id:"dossiers",l:"Dossi\u00eas",i:"\ud83d\udcda"},{id:"presentations",l:"Visual",i:"\ud83d\udcca"},{id:"studio",l:"Studio",i:"\ud83c\udfac"},{id:"kb",l:"KB",i:"\ud83e\udde0"},{id:"pipeline",l:"Pipeline",i:"\u2699\ufe0f"},{id:"traces",l:"Traces",i:"\ud83d\udce1"},{id:"jobs",l:"Jobs",i:"\ud83d\udd04"},{id:"tasks",l:"Tarefas",i:"\ud83d\udccb"},{id:"calendar",l:"Agenda",i:"\ud83d\udcc5"},{id:"audit",l:"Audit",i:"\ud83d\udd0e"}];

export default function Dashboard(){
  const[tab,setTab]=useState("overview");
  const[stats,SS]=useState<any>(null);
  const[jobs,SJ]=useState<any[]>([]);const[tasks,ST2]=useState<any[]>([]);const[events,SE]=useState<any[]>([]);const[audit,SA]=useState<any[]>([]);
  const[research,SR]=useState<any[]>([]);const[selR,SSR]=useState<any>(null);
  const[dossiers,SD]=useState<any[]>([]);const[selD,SSD]=useState<any>(null);
  const[pres,SP]=useState<any[]>([]);const[selP,SSP]=useState<any>(null);
  const[evidence,SEV]=useState<any[]>([]);const[branches,SB2]=useState<any[]>([]);
  const[qgates,SQ]=useState<any[]>([]);const[studio,SST]=useState<any[]>([]);
  const[traces,STR]=useState<any[]>([]);const[kb,SKB]=useState<any[]>([]);
  const[pipes,SPP]=useState<any[]>([]);
  const[loading,SL]=useState(true);const[lastUp,SLU]=useState<Date|null>(null);
  const[err,SER]=useState<string|null>(null);const[pulse,SPU]=useState(false);const[genL,SGL]=useState<string|null>(null);

  const fetchAll=useCallback(async()=>{
    try{SPU(true);
      const[s,j,t,e,a,rr,dd,pp,ev,br,qg,st,tr,k,pi]=await Promise.all([
        rpc<any>("get_dashboard_stats"),rpc<any[]>("get_recent_jobs",{p_limit:20}),rpc<any[]>("get_all_tasks"),rpc<any[]>("get_all_calendar_events"),rpc<any[]>("get_recent_events",{p_limit:30}),rpc<any[]>("get_all_research_reports"),rpc<any[]>("get_all_dossiers"),rpc<any[]>("get_all_presentations"),
        rpc<any[]>("get_evidence_dashboard",{p_limit:50}),rpc<any[]>("get_branches_dashboard"),rpc<any[]>("get_quality_gates_dashboard"),rpc<any[]>("get_studio_outputs"),rpc<any[]>("get_traces_dashboard",{p_limit:50}),rpc<any[]>("get_knowledge_base",{p_limit:50}),rpc<any[]>("get_pipeline_configs")
      ]);
      SS(s);SJ(j||[]);ST2(t||[]);SE(e||[]);SA(a||[]);SR(rr||[]);SD(dd||[]);SP(pp||[]);SEV(ev||[]);SB2(br||[]);SQ(qg||[]);SST(st||[]);STR(tr||[]);SKB(k||[]);SPP(pi||[]);SLU(new Date());SER(null);
    }catch(e:any){SER(e.message||"Erro");}
    finally{SL(false);setTimeout(()=>SPU(false),600);}
  },[]);
  useEffect(()=>{fetchAll();const iv=setInterval(fetchAll,12000);return()=>clearInterval(iv);},[fetchAll]);

  if(loading)return<div style={{minHeight:"100vh",background:"#050810",display:"flex",alignItems:"center",justifyContent:"center",flexDirection:"column",gap:16}}><div style={{width:44,height:44,border:"3px solid rgba(124,156,255,0.15)",borderTopColor:"#7c9cff",borderRadius:"50%",animation:"spin .8s linear infinite"}}/><div style={{color:"rgba(255,255,255,0.3)",fontSize:13,fontWeight:600,letterSpacing:1}}>CONECTANDO</div></div>;

  const sw=(t:string)=>{setTab(t);SSR(null);SSD(null);SSP(null);};
  async function gs(st:string,si:string,f:string){SGL(f);await call(SB+"/functions/v1/studio-agent",{source_type:st,source_id:si,format:f});setTimeout(fetchAll,4000);setTimeout(()=>SGL(null),5000);}

  return<div style={{minHeight:"100vh",color:"#fff",background:"#050810",fontFamily:"'Outfit',system-ui,sans-serif",position:"relative",overflow:"hidden"}}>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;600&family=Outfit:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet"/>
    <style>{`@keyframes spin{to{transform:rotate(360deg)}}@keyframes glow{0%,100%{opacity:.3}50%{opacity:.6}}@keyframes fadeUp{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}::-webkit-scrollbar{width:3px}::-webkit-scrollbar-thumb{background:rgba(124,156,255,0.2);border-radius:4px}*{box-sizing:border-box;margin:0;padding:0}.mh2{font-size:18px;font-weight:800;color:#dce5ff;margin:22px 0 10px;border-bottom:1px solid rgba(124,156,255,0.12);padding-bottom:6px}.mh3{font-size:15px;font-weight:700;color:#7c9cff;margin:16px 0 6px}.mb{color:#dce5ff}.ml{display:flex;gap:8px;margin:3px 0 3px 10px;line-height:1.6}.md{color:#7c9cff}.ma{color:#7c9cff;text-decoration:underline}.mp{line-height:1.7;margin:4px 0;color:#94a3c4}@media print{.np{display:none!important}}`}</style>
    <div style={{position:"fixed",top:-250,left:-250,width:700,height:700,borderRadius:"50%",background:"radial-gradient(circle,rgba(124,156,255,0.05),transparent 70%)",pointerEvents:"none"}}/>

    {/* HEADER */}
    <header className="np" style={{padding:"18px 24px",display:"flex",alignItems:"center",justifyContent:"space-between",borderBottom:"1px solid "+V.l}}>
      <div style={{display:"flex",alignItems:"center",gap:12}}>
        <div style={{width:36,height:36,borderRadius:10,background:"linear-gradient(135deg,#7c9cff,#4ee3c1)",display:"grid",placeItems:"center",fontSize:16,boxShadow:"0 4px 20px rgba(124,156,255,0.3)"}}>{"\ud83c\udf0d"}</div>
        <div><div style={{fontSize:15,fontWeight:800,letterSpacing:-.3}}>MUNDO ROBERTH</div><div style={{fontSize:9,color:V.m,fontWeight:600,letterSpacing:2}}>v1.0 \u00b7 ARCH v4 \u00b7 AUTO-PIPELINE</div></div>
      </div>
      <div style={{display:"flex",alignItems:"center",gap:12}}>
        <div style={{display:"flex",alignItems:"center",gap:5,padding:"4px 10px",borderRadius:16,background:"rgba(34,197,94,0.06)",border:"1px solid rgba(34,197,94,0.12)"}}><div style={{width:5,height:5,borderRadius:"50%",background:"#22c55e",boxShadow:"0 0 6px rgba(34,197,94,0.6)",animation:pulse?"glow .6s ease":"none"}}/><span style={{fontSize:9,color:"#22c55e",fontWeight:700}}>LIVE</span></div>
        <span style={{fontSize:9,color:V.m}}>{lastUp?ago(lastUp.toISOString()):""}</span>
        <button onClick={fetchAll} style={{background:"rgba(255,255,255,0.03)",border:"1px solid "+V.l,borderRadius:8,padding:"5px 10px",color:V.m,cursor:"pointer",fontSize:10,fontWeight:600}}>{"\u21bb"}</button>
      </div>
    </header>

    {/* NAV */}
    <nav className="np" style={{padding:"0 24px",display:"flex",gap:2,borderBottom:"1px solid "+V.l,overflowX:"auto"}}>
      {TABS.map(t=><button key={t.id} onClick={()=>sw(t.id)} style={{padding:"10px 11px",background:"none",border:"none",cursor:"pointer",color:tab===t.id?"#fff":"rgba(255,255,255,0.25)",fontSize:11,fontWeight:tab===t.id?700:400,borderBottom:tab===t.id?"2px solid #7c9cff":"2px solid transparent",display:"flex",alignItems:"center",gap:3,whiteSpace:"nowrap",transition:"all .2s"}}><span style={{fontSize:12}}>{t.i}</span>{t.l}</button>)}
    </nav>

    {err&&<div style={{margin:"12px 24px",padding:"8px 12px",borderRadius:10,background:"rgba(239,68,68,0.06)",border:"1px solid rgba(239,68,68,0.12)",color:"#ef4444",fontSize:11}}>{err}</div>}

    <main style={{padding:"18px 24px",animation:"fadeUp .3s ease"}}>

    {/* OVERVIEW */}
    {tab==="overview"&&stats&&<><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(120px,1fr))",gap:10,marginBottom:18}}>
      <Stat label="Pesquisas" value={stats.total_research} icon={"\ud83d\udd0d"} color="rgba(124,156,255,.08)"/>
      <Stat label="Fontes" value={stats.total_sources} icon={"\ud83d\udd17"} color="rgba(78,227,193,.08)"/>
      <Stat label="Evid\u00eancias" value={stats.total_evidence} icon={"\ud83e\uddea"} color="rgba(255,200,107,.08)"/>
      <Stat label="Ramos" value={stats.total_branches} icon={"\ud83c\udf3f"} color="rgba(124,156,255,.08)"/>
      <Stat label="Q.Gates" value={(stats.quality_gates_passed||0)+"/"+(stats.quality_gates_total||0)} icon={"\ud83d\udee1\ufe0f"} color="rgba(111,226,163,.08)"/>
      <Stat label="Dossi\u00eas" value={stats.total_dossiers} icon={"\ud83d\udcda"} color="rgba(78,227,193,.08)"/>
      <Stat label="Visual" value={stats.total_presentations} icon={"\ud83d\udcca"} color="rgba(255,125,125,.08)"/>
      <Stat label="Studio" value={stats.studio_outputs} icon={"\ud83c\udfac"} color="rgba(124,156,255,.08)"/>
      <Stat label="KB" value={stats.kb_entries||0} icon={"\ud83e\udde0"} color="rgba(78,227,193,.08)"/>
      <Stat label="Sucesso" value={(stats.success_rate||0)+"%"} icon={"\ud83d\udcc8"} color="rgba(111,226,163,.08)"/>
      <Stat label="Traces" value={stats.traces} icon={"\ud83d\udce1"} color="rgba(255,200,107,.08)"/>
      <Stat label="Handoffs" value={stats.handoffs||0} icon={"\ud83e\udd1d"} color="rgba(124,156,255,.08)"/>
    </div>
    <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>
      <Sec title="Jobs Recentes" icon={"\ud83d\udd04"}>{jobs.slice(0,6).map((j:any,i:number)=><div key={j.id} style={{padding:"7px 0",borderBottom:"1px solid rgba(255,255,255,0.03)",display:"flex",justifyContent:"space-between",alignItems:"center",animation:`fadeUp .3s ease ${.03*i}s both`}}><div style={{flex:1,minWidth:0}}><div style={{fontSize:11,fontWeight:600,color:"rgba(255,255,255,0.7)",overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{j.user_message||"\u2014"}</div><div style={{fontSize:9,color:V.m}}>{j.action||"..."} \u00b7 {ago(j.created_at)}</div></div><B s={j.status}/></div>)}</Sec>
      <Sec title="Auditoria" icon={"\ud83d\udd0e"}>{audit.slice(0,8).map((e:any,i:number)=><div key={e.id} style={{padding:"6px 0",borderBottom:"1px solid rgba(255,255,255,0.02)",animation:`fadeUp .3s ease ${.02*i}s both`}}><div style={{display:"flex",alignItems:"center",gap:5}}><B s={e.status}/><span style={{fontSize:9,color:V.m}}>{ago(e.created_at)}</span></div><div style={{fontSize:10,color:"rgba(255,255,255,0.4)",marginTop:2,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{e.message}</div></div>)}</Sec>
    </div></>}

    {/* RESEARCH */}
    {tab==="research"&&(selR?<div style={{animation:"fadeUp .3s ease"}}><button onClick={()=>SSR(null)} style={{background:V.g,border:"1px solid "+V.l,borderRadius:10,padding:"6px 12px",color:V.m,cursor:"pointer",fontSize:11,fontWeight:600,marginBottom:14}}>{"\u2190 Voltar"}</button><Card style={{marginBottom:14,background:"linear-gradient(180deg,rgba(124,156,255,0.05),rgba(255,255,255,0.02))"}}><h1 style={{fontSize:"clamp(20px,3vw,30px)",fontWeight:900,letterSpacing:"-.02em",margin:"0 0 8px"}}>{selR.topic}</h1><p style={{color:V.s,fontSize:13,margin:"0 0 12px"}}>{(selR.executive_summary||"").substring(0,200)}</p><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{[["\ud83d\udcca",selR.sources_count+" fontes"],["\ud83c\udf3f",(selR.branches?.length||0)+" ramos"],["\ud83c\udfaf",selR.confidence||"\u2014"]].map(([i,v]:any,k:number)=><span key={k} style={{padding:"5px 9px",background:"rgba(255,255,255,0.03)",border:"1px solid "+V.l,borderRadius:999,color:V.s,fontSize:11}}>{i} {v}</span>)}</div><div style={{display:"flex",gap:5,marginTop:12,flexWrap:"wrap"}}>{["executive_summary","swot","mindmap","datatable","sources_view","report"].map(f=><button key={f} disabled={genL===f} onClick={()=>gs("research",selR.id,f)} style={{padding:"5px 9px",borderRadius:8,border:"1px solid "+V.l,background:genL===f?"rgba(124,156,255,0.1)":V.g,color:genL===f?V.a:V.s,cursor:"pointer",fontSize:10,fontWeight:600}}>{"\ud83c\udfac"} {f.replace(/_/g," ")}</button>)}</div></Card>{selR.branches?.length>0&&<Card style={{marginBottom:14}}><h3 style={{fontSize:14,fontWeight:700,margin:"0 0 10px"}}>{"\ud83c\udf3f"} Ramos</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(200px,1fr))",gap:8}}>{selR.branches.map((b:any,i:number)=><div key={i} style={{padding:"10px 12px",borderRadius:12,border:"1px solid "+V.l}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:4}}><strong style={{color:V.t,fontSize:11}}>{b.branch_name}</strong><B s={b.status}/></div><div style={{fontSize:10,color:V.m}}>{b.branch_type} \u00b7 {b.sources_found} fontes</div></div>)}</div></Card>}<Card><div style={{color:V.s,lineHeight:1.75,fontSize:13}} dangerouslySetInnerHTML={{__html:md2h(selR.full_report||selR.main_answer||"")}}/></Card></div>
    :<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{research.map((r:any,i:number)=><div key={r.id} onClick={()=>r.status==="completed"&&SSR(r)} style={{background:V.g,border:"1px solid "+V.l,borderRadius:V.R,padding:"18px 20px",cursor:r.status==="completed"?"pointer":"default",transition:"all .2s",animation:`fadeUp .3s ease ${.04*i}s both`}} onMouseEnter={(e:any)=>{if(r.status==="completed")e.currentTarget.style.borderColor="rgba(124,156,255,0.2)";}} onMouseLeave={(e:any)=>{e.currentTarget.style.borderColor=V.l;}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><B s={r.status}/><span style={{fontSize:9,color:V.m}}>{ago(r.created_at)}</span></div><h3 style={{fontSize:13,fontWeight:800,margin:"0 0 5px",lineHeight:1.3}}>{r.topic}</h3><div style={{display:"flex",gap:8,fontSize:9,color:V.m}}><span>{"\ud83d\udcca"} {r.sources_count}</span>{r.branches?.length>0&&<span>{"\ud83c\udf3f"} {r.branches.length}</span>}</div></div>)}{!research.length&&<div style={{padding:40,textAlign:"center",color:"rgba(255,255,255,0.12)",gridColumn:"1/-1"}}><div style={{fontSize:40}}>{"\ud83d\udd0d"}</div><div style={{fontSize:13,fontWeight:700,marginTop:8}}>Nenhuma pesquisa</div></div>}</div>)}

    {/* EVIDENCE */}
    {tab==="evidence"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800,margin:"0 0 4px"}}>{"\ud83e\uddea"} N\u00facleo de Evid\u00eancias ({evidence.length})</h2></div><div style={{display:"grid",gap:8}}>{evidence.map((e:any,i:number)=><Card key={e.id} style={{animation:`fadeUp .3s ease ${.02*i}s both`}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:10}}><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:V.t,marginBottom:4}}>{e.claim}</div>{e.evidence&&<div style={{fontSize:11,color:V.s,lineHeight:1.5,marginBottom:4}}>{e.evidence.substring(0,200)}</div>}<div style={{display:"flex",gap:6}}><span style={{fontSize:9,padding:"2px 6px",borderRadius:8,background:"rgba(124,156,255,0.08)",color:V.a}}>{e.evidence_class}</span><span style={{fontSize:9,padding:"2px 6px",borderRadius:8,background:"rgba(255,255,255,0.04)",color:V.m}}>{e.source_type}</span></div></div><div style={{textAlign:"right",minWidth:55}}><div style={{fontSize:18,fontWeight:800,color:e.confidence>=0.7?V.ok:e.confidence>=0.4?V.w:V.r}}>{(e.confidence*100).toFixed(0)}%</div><div style={{fontSize:8,color:V.m}}>conf.</div></div></div></Card>)}</div></>}

    {/* BRANCHES */}
    {tab==="branches"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83c\udf3f"} Ramos ({branches.length})</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:10}}>{branches.map((b:any,i:number)=><Card key={b.id} style={{animation:`fadeUp .3s ease ${.02*i}s both`,borderLeft:"3px solid "+(b.status==="completed"?V.ok:b.status==="failed"?V.r:V.w)}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><strong style={{color:V.t,fontSize:12}}>{b.branch_name}</strong><B s={b.status}/></div><div style={{fontSize:10,color:V.a,marginBottom:4}}>{b.research_topic?.substring(0,50)}</div><div style={{display:"flex",gap:8,fontSize:10,color:V.m}}><span>{"\ud83d\udcca"} {b.sources_found}</span><span>{"\ud83e\uddea"} {b.evidence_count}</span>{b.duration_ms&&<span>{"\u23f1"} {(b.duration_ms/1000).toFixed(1)}s</span>}</div></Card>)}</div></>}

    {/* QUALITY GATES */}
    {tab==="quality"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83d\udee1\ufe0f"} Quality Gates ({qgates.filter((g:any)=>g.gate_status==="passed").length}/{qgates.length})</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(260px,1fr))",gap:10}}>{qgates.map((g:any,i:number)=><Card key={g.id} style={{animation:`fadeUp .3s ease ${.02*i}s both`,background:g.gate_status==="passed"?"rgba(34,197,94,0.03)":"rgba(251,191,36,0.03)"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><strong style={{color:V.t,fontSize:12,textTransform:"uppercase"}}>{g.gate_name}</strong><B s={g.gate_status}/></div><div style={{fontSize:10,color:V.a,marginBottom:6}}>{g.entity_title?.substring(0,50)}</div><div style={{display:"flex",alignItems:"center",gap:8}}><div style={{flex:1,height:6,borderRadius:999,background:"rgba(255,255,255,0.06)",overflow:"hidden"}}><div style={{height:"100%",width:Math.min(100,(g.actual_value||0)/(g.threshold||1)*100)+"%",borderRadius:999,background:g.gate_status==="passed"?"linear-gradient(90deg,#7c9cff,#4ee3c1)":"#fbbf24"}}/></div><span style={{fontSize:10,fontWeight:700,color:V.t}}>{g.actual_value}/{g.threshold}</span></div></Card>)}</div></>}

    {/* DOSSIERS */}
    {tab==="dossiers"&&(selD?<div style={{animation:"fadeUp .3s ease"}}><button onClick={()=>SSD(null)} style={{background:V.g,border:"1px solid "+V.l,borderRadius:10,padding:"6px 12px",color:V.m,cursor:"pointer",fontSize:11,fontWeight:600,marginBottom:14}}>{"\u2190"}</button><Card style={{marginBottom:14,border:"1px solid rgba(78,227,193,0.12)"}}><h1 style={{fontSize:"clamp(18px,3vw,28px)",fontWeight:900,margin:"0 0 8px"}}>{selD.title}</h1><div style={{display:"flex",gap:5,marginTop:10}}><button onClick={()=>window.print()} style={{padding:"7px 12px",borderRadius:10,border:"none",background:"linear-gradient(135deg,"+V.a+","+V.a2+")",color:"#050810",cursor:"pointer",fontSize:11,fontWeight:700}}>{"\ud83d\udcc4"} PDF</button>{["executive_summary","swot","mindmap"].map(f=><button key={f} onClick={()=>gs("dossier",selD.id,f)} style={{padding:"5px 9px",borderRadius:8,border:"1px solid "+V.l,background:V.g,color:V.s,cursor:"pointer",fontSize:10,fontWeight:600}}>{"\ud83c\udfac"} {f.replace(/_/g," ")}</button>)}</div></Card><Card><div style={{color:V.s,lineHeight:1.8,fontSize:13}} dangerouslySetInnerHTML={{__html:md2h(selD.detailed_analysis||selD.executive_summary||"")}}/></Card></div>
    :<div><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83d\udcda"} Dossi\u00eas ({dossiers.filter((d:any)=>d.status==="completed").length})</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{dossiers.filter((d:any)=>d.status==="completed").map((d:any)=><div key={d.id} onClick={()=>SSD(d)} style={{background:V.g,border:"1px solid rgba(78,227,193,0.1)",borderRadius:V.R,padding:"18px 20px",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><B s={d.status}/><span style={{fontSize:9,color:V.m}}>{ago(d.created_at)}</span></div><h3 style={{fontSize:13,fontWeight:800,margin:"0 0 10px"}}>{d.title}</h3><div style={{fontSize:9,color:V.m}}>{"\ud83d\udcca"} {d.sources_analyzed}+{d.new_sources_found} \u00b7 <span style={{color:V.a2}}>Abrir {"\u2192"}</span></div></div>)}{research.filter((r:any)=>r.status==="completed"&&!dossiers.find((d:any)=>d.original_research?.id===r.id)).map((r:any)=><div key={r.id} style={{background:V.g,border:"1px solid "+V.l,borderRadius:V.R,padding:"18px 20px"}}><div style={{fontSize:9,color:V.m,marginBottom:6}}>{"\ud83d\udd0d"} {r.sources_count} fontes</div><h3 style={{fontSize:12,fontWeight:700,margin:"0 0 10px"}}>{r.topic}</h3><button onClick={async()=>{SGL(r.id);await call(SB+"/functions/v1/dossier-agent",{report_id:r.id});setTimeout(fetchAll,4000);SGL(null);}} style={{width:"100%",padding:"7px",borderRadius:10,border:"none",background:"linear-gradient(135deg,"+V.a+","+V.a2+")",color:"#050810",cursor:"pointer",fontSize:11,fontWeight:700}}>{"\ud83d\udcda"} Gerar Dossi\u00ea</button></div>)}</div></div>)}

    {/* PRESENTATIONS */}
    {tab==="presentations"&&(selP?<div style={{animation:"fadeUp .3s ease"}}><button className="np" onClick={()=>SSP(null)} style={{background:V.g,border:"1px solid "+V.l,borderRadius:10,padding:"6px 12px",color:V.m,cursor:"pointer",fontSize:11,marginBottom:14}}>{"\u2190"}</button>{selP.hero_section&&<Card style={{marginBottom:14,border:"1px solid rgba(255,200,107,0.12)",padding:28}}><h1 style={{fontSize:"clamp(22px,3vw,36px)",fontWeight:900,margin:"0 0 8px",lineHeight:1.15}}>{selP.title}</h1><p style={{color:V.s,fontSize:14,maxWidth:700,lineHeight:1.7}}>{selP.hero_section.summary||selP.subtitle}</p><button className="np" onClick={()=>window.print()} style={{padding:"8px 14px",borderRadius:10,border:"none",background:"linear-gradient(135deg,#ffc86b,"+V.a2+")",color:"#050810",cursor:"pointer",fontSize:12,fontWeight:700,marginTop:12}}>{"\ud83d\udcc4"} PDF</button></Card>}{selP.highlights?.length>0&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(130px,1fr))",gap:10,marginBottom:14}}>{selP.highlights.map((h:any,i:number)=><Card key={i} style={{textAlign:"center",padding:14}}><div style={{fontSize:22}}>{h.icon||"\ud83d\udccc"}</div><div style={{fontSize:22,fontWeight:800}}>{h.value}</div><div style={{fontSize:10,color:V.m}}>{h.label}</div></Card>)}</div>}{selP.executive_summary&&<Card style={{marginBottom:14}}><h2 style={{fontSize:16,fontWeight:800,margin:"0 0 10px"}}>{"\ud83d\udcdd"} Resumo</h2><div style={{color:V.s,lineHeight:1.8,fontSize:13}} dangerouslySetInnerHTML={{__html:md2h(selP.executive_summary)}}/></Card>}{(selP.sections||[]).map((s:any,i:number)=><Card key={i} style={{marginBottom:14}}><h2 style={{fontSize:16,fontWeight:800,margin:"0 0 10px"}}>{s.icon||""} {s.title}</h2>{s.type==="cards"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:10}}>{(s.items||[]).map((it:any,j:number)=><Card key={j}><h3 style={{fontSize:13,fontWeight:700,margin:"0 0 4px"}}>{it.title}</h3><p style={{color:V.s,fontSize:11,margin:0}}>{it.content}</p></Card>)}</div>:<div style={{color:V.s,lineHeight:1.8,fontSize:13}} dangerouslySetInnerHTML={{__html:md2h(s.content||"")}}/>}</Card>)}{selP.conclusion&&<Card style={{border:"1px solid rgba(78,227,193,0.12)"}}><h2 style={{fontSize:16,fontWeight:800,margin:"0 0 10px",color:V.a2}}>{"\u2705"} Conclus\u00e3o</h2><div style={{color:V.s,lineHeight:1.8,fontSize:13}} dangerouslySetInnerHTML={{__html:md2h(selP.conclusion)}}/></Card>}</div>
    :<div><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83d\udcca"} Apresenta\u00e7\u00f5es</h2></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12}}>{pres.filter((p:any)=>p.status==="completed").map((p:any)=><div key={p.id} onClick={()=>SSP(p)} style={{background:V.g,border:"1px solid rgba(255,200,107,0.1)",borderRadius:V.R,padding:"18px 20px",cursor:"pointer"}}><B s={p.status}/><h3 style={{fontSize:13,fontWeight:800,margin:"8px 0 6px"}}>{p.title}</h3><div style={{fontSize:9,color:V.m}}>{p.total_sections} se\u00e7\u00f5es \u00b7 <span style={{color:"#ffc86b"}}>Abrir {"\u2192"}</span></div></div>)}</div></div>)}

    {/* STUDIO */}
    {tab==="studio"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83c\udfac"} Studio ({studio.length})</h2><p style={{color:V.m,fontSize:12}}>Mesmos dados, m\u00faltiplos formatos</p></div>{studio.length>0?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:10}}>{studio.map((s:any,i:number)=><Card key={s.id} style={{animation:`fadeUp .3s ease ${.02*i}s both`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{padding:"3px 8px",borderRadius:8,background:"rgba(124,156,255,0.08)",color:V.a,fontSize:10,fontWeight:700}}>{s.output_format}</span><span style={{fontSize:9,color:V.m}}>{ago(s.created_at)}</span></div><h3 style={{fontSize:12,fontWeight:700,margin:"0 0 6px",color:V.t}}>{s.title}</h3><div style={{fontSize:10,color:V.s,maxHeight:80,overflow:"hidden"}}>{(s.content||"").substring(0,200)}</div></Card>)}</div>:<div style={{padding:40,textAlign:"center",color:"rgba(255,255,255,0.12)"}}><div style={{fontSize:40}}>{"\ud83c\udfac"}</div><div style={{fontSize:13,fontWeight:700,marginTop:8}}>Use bot\u00f5es {"\ud83c\udfac"} nas pesquisas</div></div>}</>}

    {/* KNOWLEDGE BASE */}
    {tab==="kb"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83e\udde0"} Knowledge Base ({kb.length})</h2><p style={{color:V.m,fontSize:12}}>Mande "Anotar: ..." no Telegram para salvar conhecimento</p></div>{kb.length>0?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:10}}>{kb.map((k:any,i:number)=><Card key={k.id} style={{animation:`fadeUp .3s ease ${.02*i}s both`}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><span style={{padding:"2px 8px",borderRadius:8,background:"rgba(78,227,193,0.08)",color:V.a2,fontSize:10,fontWeight:700}}>{k.content_type}</span><span style={{fontSize:9,color:V.m}}>{ago(k.created_at)}</span></div><h3 style={{fontSize:13,fontWeight:700,margin:"0 0 6px"}}>{k.title}</h3><div style={{fontSize:11,color:V.s,lineHeight:1.5}}>{k.content.substring(0,200)}</div>{k.tags?.length>0&&<div style={{display:"flex",gap:4,flexWrap:"wrap",marginTop:8}}>{k.tags.map((t:string,j:number)=><span key={j} style={{padding:"2px 6px",borderRadius:6,background:"rgba(255,255,255,0.04)",color:V.m,fontSize:9}}>#{t}</span>)}</div>}</Card>)}</div>:<div style={{padding:50,textAlign:"center",color:"rgba(255,255,255,0.12)"}}><div style={{fontSize:50}}>{"\ud83e\udde0"}</div><div style={{fontSize:14,fontWeight:700,marginTop:10}}>Knowledge Base vazia</div><div style={{fontSize:12,color:V.m,marginTop:6,maxWidth:400,margin:"6px auto"}}>Mande "Anotar: meu gado Nelore pesa em m\u00e9dia 450kg" ou "Salvar: pre\u00e7o do milho R$65/saca" no Telegram</div></div>}</>}

    {/* PIPELINE */}
    {tab==="pipeline"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\u2699\ufe0f"} Auto-Pipeline</h2><p style={{color:V.m,fontSize:12}}>Pesquisa {"\u2192"} Dossi\u00ea {"\u2192"} Apresenta\u00e7\u00e3o autom\u00e1tico</p></div><div style={{display:"grid",gap:12}}>
      {/* Pipeline visual */}
      <Card style={{background:"linear-gradient(135deg,rgba(124,156,255,0.04),rgba(78,227,193,0.03))",padding:24}}>
        <div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:12,flexWrap:"wrap"}}>
          {[{icon:"\ud83d\udcac",label:"Telegram",color:V.a},{icon:"\ud83d\udd0d",label:"Research v15",color:V.a},{icon:"\ud83c\udf3f",label:"Branches",color:V.a2},{icon:"\ud83e\uddea",label:"Evidence",color:V.w},{icon:"\ud83d\udee1\ufe0f",label:"Q.Gates",color:V.ok},{icon:"\ud83d\udcda",label:"Dossier v7",color:V.a2},{icon:"\ud83d\udcca",label:"Presentation v4",color:V.w},{icon:"\ud83c\udfac",label:"Studio v2",color:V.a}].map((s,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:8}}>
            <div style={{width:48,height:48,borderRadius:12,background:"rgba(255,255,255,0.05)",border:"1px solid "+V.l,display:"grid",placeItems:"center"}}><div style={{fontSize:20}}>{s.icon}</div></div>
            <div><div style={{fontSize:11,fontWeight:700,color:V.t}}>{s.label}</div></div>
            {i<7&&<div style={{color:"rgba(255,255,255,0.15)",fontSize:18,margin:"0 4px"}}>{"\u2192"}</div>}
          </div>)}
        </div>
      </Card>
      {/* Pipeline configs */}
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:10}}>
        {pipes.map((p:any,i:number)=><Card key={p.id} style={{borderLeft:"3px solid "+(p.is_active?V.ok:"rgba(255,255,255,0.1)")}}>
          <div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}>
            <strong style={{color:V.t,fontSize:12}}>{p.action.replace(/_/g," ").toUpperCase()}</strong>
            <span style={{padding:"2px 8px",borderRadius:8,background:p.is_active?"rgba(34,197,94,0.1)":"rgba(255,255,255,0.04)",color:p.is_active?V.ok:V.m,fontSize:10,fontWeight:700}}>{p.is_active?"ATIVO":"INATIVO"}</span>
          </div>
          <div style={{fontSize:11,color:V.s}}>Trigger: <strong style={{color:V.a}}>{p.trigger_event}</strong></div>
          {p.config&&<div style={{fontSize:10,color:V.m,marginTop:4}}>{JSON.stringify(p.config)}</div>}
          <button onClick={async()=>{await sb.from("pipeline_configs").update({is_active:!p.is_active}).eq("id",p.id);fetchAll();}} style={{marginTop:8,padding:"5px 10px",borderRadius:8,border:"1px solid "+V.l,background:V.g,color:p.is_active?V.r:V.ok,cursor:"pointer",fontSize:10,fontWeight:600}}>{p.is_active?"Desativar":"Ativar"}</button>
        </Card>)}
      </div>
    </div></>}

    {/* TRACES */}
    {tab==="traces"&&<><div style={{marginBottom:16}}><h2 style={{fontSize:18,fontWeight:800}}>{"\ud83d\udce1"} Traces ({traces.length})</h2></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{borderBottom:"1px solid "+V.l}}>{["Agent","Step","Output","Dur.","Status","Data"].map(h=><th key={h} style={{padding:"8px 6px",textAlign:"left",color:V.m,fontSize:9,fontWeight:700,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{traces.map((t:any,i:number)=><tr key={t.id} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"6px",color:V.a,fontWeight:600,fontSize:10}}>{t.agent_name?.split("-").pop()}</td><td style={{padding:"6px",color:V.t}}>{t.step}</td><td style={{padding:"6px",color:V.s,maxWidth:180,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{t.output_summary||"\u2014"}</td><td style={{padding:"6px",fontFamily:"'JetBrains Mono',monospace",fontSize:10,color:t.duration_ms>10000?V.r:t.duration_ms>3000?V.w:V.ok}}>{t.duration_ms?(t.duration_ms/1000).toFixed(1)+"s":"\u2014"}</td><td style={{padding:"6px"}}><B s={t.status||"ok"}/></td><td style={{padding:"6px",color:V.m,fontSize:9}}>{fmt(t.created_at)}</td></tr>)}</tbody></table></div></>}

    {/* JOBS */}
    {tab==="jobs"&&<Sec title={"Jobs ("+jobs.length+")"} icon={"\ud83d\udd04"} full><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr style={{borderBottom:"1px solid "+V.l}}>{["Status","Msg","A\u00e7\u00e3o","Q","Agente","Data"].map(h=><th key={h} style={{padding:"6px",textAlign:"left",color:V.m,fontSize:9,fontWeight:700,textTransform:"uppercase"}}>{h}</th>)}</tr></thead><tbody>{jobs.map((j:any)=><tr key={j.id} style={{borderBottom:"1px solid rgba(255,255,255,0.02)"}}><td style={{padding:"6px"}}><B s={j.status}/></td><td style={{padding:"6px",color:V.s,maxWidth:200,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{j.user_message||"\u2014"}</td><td style={{padding:"6px",color:V.a,fontWeight:600}}>{j.action||"\u2014"}</td><td style={{padding:"6px"}}>{j.quality_score?<span style={{color:j.quality_score>=.8?V.ok:V.w}}>{(j.quality_score*100).toFixed(0)}%</span>:"\u2014"}</td><td style={{padding:"6px",color:V.m,fontSize:9}}>{j.agent_version||"\u2014"}</td><td style={{padding:"6px",color:V.m,fontSize:9}}>{fmt(j.created_at)}</td></tr>)}</tbody></table></Sec>}

    {tab==="tasks"&&<Sec title={"Tarefas ("+tasks.length+")"} icon={"\ud83d\udccb"} full>{tasks.map((t:any)=><div key={t.id} style={{padding:"10px 4px",borderBottom:"1px solid rgba(255,255,255,0.02)",display:"flex",justifyContent:"space-between"}}><div><div style={{fontSize:12,fontWeight:700,color:V.t}}>{t.title}</div>{t.due_at&&<div style={{fontSize:9,color:V.m}}>Prazo: {fmt(t.due_at)}</div>}</div><B s={t.status}/></div>)}{!tasks.length&&<div style={{padding:30,textAlign:"center",color:V.m}}>Nenhuma tarefa</div>}</Sec>}

    {tab==="calendar"&&<Sec title={"Agenda ("+events.length+")"} icon={"\ud83d\udcc5"} full>{events.map((e:any)=><div key={e.id} style={{padding:"10px 4px",borderBottom:"1px solid rgba(255,255,255,0.02)",display:"flex",gap:10}}><div style={{minWidth:40,textAlign:"center",padding:4,borderRadius:6,background:"rgba(124,156,255,0.06)"}}><div style={{fontSize:14,fontWeight:800,color:V.a}}>{new Date(e.start_at).getDate()}</div></div><div style={{flex:1}}><div style={{fontSize:12,fontWeight:700,color:V.t}}>{e.title}</div><div style={{fontSize:9,color:V.m}}>{e.all_day?"Dia inteiro":fmt(e.start_at)}</div></div><B s={e.status}/></div>)}{!events.length&&<div style={{padding:30,textAlign:"center",color:V.m}}>Nenhum evento</div>}</Sec>}

    {tab==="audit"&&<Sec title={"Auditoria ("+audit.length+")"} icon={"\ud83d\udd0e"} full>{audit.map((e:any,i:number)=><div key={e.id} style={{padding:"6px 4px",borderLeft:"3px solid "+(ST[e.status]||ST.pending).c,marginLeft:4,borderRadius:"0 6px 6px 0",background:i%2===0?"rgba(255,255,255,0.006)":"transparent"}}><div style={{display:"flex",gap:5,marginBottom:2}}><B s={e.status}/><span style={{fontSize:9,color:V.m}}>{fmt(e.created_at)}</span></div><div style={{fontSize:10,color:"rgba(255,255,255,0.4)"}}>{e.message}</div></div>)}</Sec>}

    </main>
    <footer className="np" style={{padding:"12px 24px",textAlign:"center",borderTop:"1px solid "+V.l}}><span style={{fontSize:9,color:"rgba(255,255,255,0.08)"}}>Mundo Roberth v1.0 \u00b7 Arch v4 \u00b7 9 Agentes \u00b7 28 Tabelas \u00b7 15 Tabs \u00b7 Auto-Pipeline \u00b7 3 Crons</span></footer>
  </div>;
}
